<a href="https://colab.research.google.com/github/LEESUAJE1978/deeplearning_sejong/blob/master/ex02_data_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0.텐서플로우 버전 선택

In [1]:
#0. 텐서플로우 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 1.x
except Exception:
    pass
import tensorflow as tf
import numpy as np

print(tf.__version__)

TensorFlow 1.x selected.
1.15.2


1. 텐서플로우 구조와 자료형

1.1. Rank & Shape

In [6]:
constant_scalar = tf.constant(1)
constant_vector = tf.constant([1,2])
constant_matrix = tf.constant([[1,2,3], [4,5,6]])
constant_narray = tf.constant([[[2],[4]], [[3],[7]], [[8],[9]]])

In [9]:
sess = tf.Session() #tf.v1에서는 Session을 실행해 주어야 함
print("OPEN SESSION")

OPEN SESSION


In [30]:
print(f"rank는: {sess.run(tf.rank(constant_scalar))}, shape은 {sess.run(tf.shape(constant_scalar))}")
print(f"rank는: {sess.run(tf.rank(constant_vector))}, shape은 {sess.run(tf.shape(constant_vector))}")
print(f"rank는: {sess.run(tf.rank(constant_matrix))}, shape은 {sess.run(tf.shape(constant_matrix))}")
print(f"rank는: {sess.run(tf.rank(constant_narray))}, shape은 {sess.run(tf.shape(constant_narray))}")

rank는: 0, shape은 []
rank는: 1, shape은 [2]
rank는: 2, shape은 [2 3]
rank는: 3, shape은 [3 2 1]


1.2 상수(Constant)

In [64]:
a = tf.constant([5],dtype=tf.float32)
b = tf.constant([10],dtype=tf.float32)
c = tf.constant([2],dtype=tf.float32)
d = a*b+c

print(d)



Tensor("add_7:0", shape=(1,), dtype=float32)


1.3. 그래프(Graph)

In [2]:
matrix1 = tf.constant([[3,3]]) #1 X 2 행렬을 만드는 constant op 생성
matrix2 = tf.constant([[2],[2]]) #2 X 1행렬을 만드는 constant op 생성
product = tf.matmul(matrix1, matrix2) 

1.4. 세션(Session)

In [3]:
sess = tf.Session() #세션 오픈
result = sess.run(product) 
print(result) #1 X 1 행렬이 생성됨
sess.close() #세션 클로징

[[12]]


In [40]:
with tf.Session() as sess:
  result = sess.run([product])
  print(result)

[array([[12]], dtype=int32)]


In [65]:
sess.close()

1.5. 플레이스홀더(placeholder)

In [68]:
input_data = [1,3,5,7,9]

x = tf.placeholder(dtype=tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y,feed_dict={x:input_data})


print(result)


[ 2.  6. 10. 14. 18.]


1.6. 변수(Variable)

In [69]:
input_data = [1,3,5,7,9]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2],dtype=tf.float32)

y = W*x

sess = tf.Session() #세션 오픈
init = tf.global_variables_initializer() #변수 초기화
sess.run(init)

result = sess.run(y,feed_dict={x:input_data})

print(result)




[ 2.  6. 10. 14. 18.]


In [58]:
state = tf.Variable(0, name = 'counter') #optional-name 설정 가능

1.6.1. 변수 더하기 및 바꾸기

In [59]:
one = tf.constant(1) # 상수 선언
new_value = tf.add(state, one) # 변수에 상수 더하기 
#new_value = tf.subtract(state, one)# 변수에 상수 빼기 
#new_value = tf.multiply(state, one)# 변수에 상수 곱하기 
#new_value = tf.div(state, one)# 변수에 상수 나누기 
update = tf.assign(state, new_value) # 새로 생성된 상수로 변수 변경하기

In [60]:
init_op = tf.global_variables_initializer()

In [55]:
with tf.Session() as sess:
  # 'init' 작업(op)을 실행합니다.
  # Run the 'init' op
  sess.run(init_op)
  # 'state'의 시작값을 출력합니다.
  # Print the initial value of 'state'
  print(sess.run(state)) #초기 값 출력
  print(sess.run(new_value)) #연산 값 출력
  print(sess.run(update)) #업데이터 값 출력

0
1
1


In [63]:
with tf.Session() as sess:
  # 'init' 작업(op)을 실행합니다.
  # Run the 'init' op
  sess.run(init_op)
  # 'state'의 시작값을 출력합니다.
  # Print the initial value of 'state'
  print(sess.run(state))
  # 'state'값을 업데이트하고 출력하는 작업(op)을 실행합니다.
  for _ in range(3):
    sess.run(update)
    print(sess.run(state))

0
1
2
3


In [57]:
sess.close()

Defining Tensor

In [ ]:
m1 = [[1.0, 2.0],
      [3.0,4.0]]
m2 = np.array([[1.0, 2.0],
      [3.0,4.0]])
m3 = tf.constant([[1.0, 2.0],
      [3.0,4.0]])    

In [ ]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [ ]:
print(m1)
print(m2)
print(m3)

[[1.0, 2.0], [3.0, 4.0]]
[[1. 2.]
 [3. 4.]]
Tensor("Const:0", shape=(2, 2), dtype=float32)


텐서로 변환하기(Tensor transformation)

In [ ]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [ ]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [ ]:
print(t1)
print(t2)
print(t3)

Tensor("Const_1:0", shape=(2, 2), dtype=float32)
Tensor("Const_2:0", shape=(2, 2), dtype=float32)
Tensor("Const:0", shape=(2, 2), dtype=float32)


In [ ]:
sess = tf.Session()
print("OPEN SESSION")

OPEN SESSION


In [ ]:
def print_tf(x):
  print("Type IS\n %s" % (type(x)))
  print("VALUE IS \n %s" % (x))

Constant

In [ ]:
hello = tf.constant("Hello World!")
print(hello)
print_tf(hello)

Tensor("Const_5:0", shape=(), dtype=string)
Type IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Const_5:0", shape=(), dtype=string)


In [ ]:
print(sess.run(hello))
sess.run(hello)

b'Hello World!'


b'Hello World!'

In [ ]:
print_tf(sess.run(hello))

Type IS
 <class 'bytes'>
VALUE IS 
 b'Hello World!'


In [ ]:
a = tf.constant(1.5)
b = tf.constant(2.5)

In [ ]:
print(a)
print_tf(b)

Tensor("Const_6:0", shape=(), dtype=float32)
Type IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Const_7:0", shape=(), dtype=float32)


In [ ]:
print_tf(sess.run(a))
print_tf(sess.run(b))

Type IS
 <class 'numpy.float32'>
VALUE IS 
 1.5
Type IS
 <class 'numpy.float32'>
VALUE IS 
 2.5


Variable

In [ ]:
weight1 = tf.Variable(tf.random_normal([5,2], stddev=0.1))
print_tf(weight1)

Type IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS 
 <tf.Variable 'Variable_2:0' shape=(5, 2) dtype=float32_ref>


In [ ]:
print(sess.run(weight1))

FailedPreconditionError: ignored

In [ ]:
sess.run(weight1.initializer)

In [ ]:
print_tf(sess.run(weight1))

Type IS
 <class 'numpy.ndarray'>
VALUE IS 
 [[-0.10471616 -0.07511031]
 [-0.05308089  0.05742311]
 [-0.0376507   0.07981583]
 [-0.01369468 -0.02734861]
 [-0.0876407   0.08783571]]


In [ ]:
weight2 = tf.Variable(tf.random_normal([5,2], stddev=0.1))
weight3 = tf.Variable(tf.random_normal([5,2], stddev=0.1))
print_tf(weight2)
print_tf(weight3)


Type IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS 
 <tf.Variable 'Variable_5:0' shape=(5, 2) dtype=float32_ref>
Type IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS 
 <tf.Variable 'Variable_6:0' shape=(5, 2) dtype=float32_ref>


In [ ]:
sess.run(weight2.initializer)
sess.run(weight3.initializer)

global initializer

In [ ]:
init = tf.global_variables_initializer()
sess.run(init)