<a href="https://colab.research.google.com/github/LEESUAJE1978/deeplearning_sejong/blob/master/ex05_mutinomial_logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0. 텐서플로우 버전 선택

In [175]:
#0. 텐서플로우 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 1.x
except Exception:
    pass
import tensorflow as tf
import numpy as np
import pandas as pd

print(tf.__version__)

1.15.2


텐서플로우 활용 다중로지스틱 회귀분석

1. set.seed 설정 set seed는 재현 가능성(reproducibility)를 위해 사용

In [178]:
tf.set_random_seed(777) #for reproducibility

2. 데이터 셋 생성


In [179]:
x_data = [[1,2,1,1,],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7],
          ]

y_data = [[0,0,1],
          [0,0,1],
          [0,0,1],
          [0,1,0],
          [0,1,0],
          [0,1,0],
          [1,0,0],
          [1,0,0]]

In [180]:
print(type(x_data)) # (4 * 8 matrix)
print(type(y_data)) #(8*3 matrix) #dummy variables, one-hot encoding

<class 'list'>
<class 'list'>


3. 플레이스 홀더 생성(Generating Placeholder)

In [181]:
X = tf.placeholder("float", [None, 4])
Y= tf.placeholder("float", [None, 3])
nb_classes = 3 #분류 대상 개수

4. 가중치 및 bias 설정(weight, bias) 설정

In [182]:
W = tf.Variable(tf.random_normal([4, 3]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]),name ='bias')

5. 가설(Hypothesis)설정

In [183]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

6. 비용함수(Cost Function) 설정

In [184]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1)) #열을 기준으로 계산


7. 경사하강법 적용(Gradient Decents)

In [185]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

8. 세션 실행

In [77]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(2001):
    _, cost_val = sess.run([optimizer, cost], feed_dict = {X:x_data, Y: y_data})
    
    if step %200 ==0:
       print(step, cost_val)
  print('X값이 [1, 11, 7, 9] 일 때, Y의 값은?')
  a = sess.run(hypothesis, feed_dict={X :[[1,11,7,9]]})
  print(a, sess.run(tf.argmax(a,1)))
  
  print('X값이 [1, 3, 4, 3] 일 때, Y의 값은?')
  b = sess.run(hypothesis, feed_dict={X :[[1,3,4,3]]})
  print(b, sess.run(tf.argmax(b,1)))

  print('X값이 [1, 1, 0, 1] 일 때, Y의 값은?')
  c = sess.run(hypothesis, feed_dict={X :[[1,1,0,1]]})
  print(c, sess.run(tf.argmax(c,1)))

  print('X값이 [1, 11, 7, 9], [1, 3, 4, 3] , [1, 1, 0, 1] 일 때, Y의 값은?')
  all = sess.run(hypothesis, feed_dict={X :[[1, 11, 7, 9], [1, 3, 4, 3],[1,1,0,1]]})
  print(all, sess.run(tf.argmax(all,1)))


0 15.37867
200 0.6412344
400 0.53935647
600 0.44857335
800 0.3594883
1000 0.2717909
1200 0.22767109
1400 0.20732816
1600 0.19018152
1800 0.175545
2000 0.162916
X값이 [1, 11, 7, 9] 일 때, Y의 값은?
[[3.3966370e-02 9.6602273e-01 1.0956867e-05]] [1]
X값이 [1, 3, 4, 3] 일 때, Y의 값은?
[[0.6589983  0.298451   0.04255062]] [0]
X값이 [1, 1, 0, 1] 일 때, Y의 값은?
[[1.7008624e-08 3.9279053e-04 9.9960726e-01]] [2]
X값이 [1, 11, 7, 9], [1, 3, 4, 3] , [1, 1, 0, 1] 일 때, Y의 값은?
[[3.3966385e-02 9.6602273e-01 1.0956868e-05]
 [6.5899849e-01 2.9845098e-01 4.2550597e-02]
 [1.7008624e-08 3.9279056e-04 9.9960726e-01]] [1 0 2]


파이썬 활용(Scikitlearn)활용

1. 패키지 불러오기

In [186]:
from sklearn.linear_model import LogisticRegression

2. 데이터 생성

In [234]:
x_data = [[1,2,1,1,],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7],
          ]

y_data = [[0,0,1],
          [0,0,1],
          [0,0,1],
          [0,1,0],
          [0,1,0],
          [0,1,0],
          [1,0,0],
          [1,0,0]]

In [235]:
print(type(x_data))
print(type(y_data))

<class 'list'>
<class 'list'>


3. 데이터 형태 변환

In [236]:
y_class = np.argmax(y_data, axis =1)
print(y_class)
print(type(y_class))

[2 2 2 1 1 1 0 0]
<class 'numpy.ndarray'>


4. 데이터 프레임 만들기

In [206]:
X, Y = pd.DataFrame(x_data), pd.DataFrame(y_class)

In [210]:
df= pd.merge(X,Y, how= 'outer', left_index=True, right_index=True)
df

0_x  1  2  3  0_y
0    1  2  1  1    2
1    2  1  3  2    2
2    3  1  3  4    2
3    4  1  5  5    1
4    1  7  5  5    1
5    1  2  5  6    1
6    1  6  6  6    0
7    1  7  7  7    0

5. 로지스틱 회귀모델 

In [237]:
clf = LogisticRegression(multi_class='multinomial', random_state=42).fit(x_data, y_class) #데이터의 배열 맞춰줘야함

In [212]:
print(clf.predict(X.iloc[1:2,]))  #값 예측하기
print(df.iloc[1:2,-1])

[2]
1    2
Name: 0_y, dtype: int64


In [213]:
clf.predict_proba(X.iloc[1:2,]) #소프트 맥스 함수 예측 값

array([[2.47837748e-04, 7.25502615e-02, 9.27201901e-01]])

In [230]:
print(clf.predict([[110,10,4,5]]))
print(clf.predict_proba([[110,10,4,5]]))
print(clf.predict([[5,100,2,4]]))
print(clf.predict_proba([[5,100,2,4]]))

[1]
[[2.13426078e-09 9.99999432e-01 5.65802510e-07]]
[0]
[[1.00000000e+00 2.71965528e-15 1.26044199e-27]]


6. tip- 데이터 형 변환

In [231]:
y_class = np.argmax(y_data, axis =1).reshape(-1,1)
y_class = y_class.ravel()
type(y_class)

numpy.ndarray

케라스활용


1. 패키지 불러오기

In [238]:
from tensorflow.keras.models import Sequential # 케라스의 Sequential()을 임포트
from tensorflow.keras.layers import Dense # 케라스의 Dense()를 임포트
from tensorflow.keras import optimizers # 케라스의 옵티마이저를 임포트

2. 데이터 셋 생성

In [239]:
x_data = [[1,2,1,1,],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7],
          ]

y_data = [[0,0,1],
          [0,0,1],
          [0,0,1],
          [0,1,0],
          [0,1,0],
          [0,1,0],
          [1,0,0],
          [1,0,0]]

In [240]:
print(type(x_data))
print(type(y_data))

<class 'list'>
<class 'list'>


3. 데이터 형 변환

In [242]:
x_data = np.array(x_data)
print(x_data)
print(type(x_data))

[[1 2 1 1]
 [2 1 3 2]
 [3 1 3 4]
 [4 1 5 5]
 [1 7 5 5]
 [1 2 5 6]
 [1 6 6 6]
 [1 7 7 7]]
<class 'numpy.ndarray'>


In [243]:
y_class = np.argmax(y_data, axis =1)
print(y_class)
print(type(y_class))

[2 2 2 1 1 1 0 0]
<class 'numpy.ndarray'>


4. 케라스 모델 구축

In [244]:
model = Sequential()
model.add(Dense(3, input_dim =4, activation='softmax'))
sgd = optimizers.SGD(learning_rate=0.01)
model.compile(loss = 'sparse_categorical_crossentropy', optimizer ='adam', metrics = ['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [247]:
history = model.fit(x_data, y_class, batch_size = 32, epochs = 20, validation_split=0.2 )

Train on 6 samples, validate on 2 samples
Epoch 1/20
6/6 [==============================] - 0s 837us/sample - loss: 1.3343 - acc: 0.5000 - val_loss: 2.8243 - val_acc: 0.0000e+00
Epoch 2/20
6/6 [==============================] - 0s 703us/sample - loss: 1.3301 - acc: 0.5000 - val_loss: 2.8413 - val_acc: 0.0000e+00
Epoch 3/20
6/6 [==============================] - 0s 638us/sample - loss: 1.3259 - acc: 0.5000 - val_loss: 2.8583 - val_acc: 0.0000e+00
Epoch 4/20
6/6 [==============================] - 0s 599us/sample - loss: 1.3218 - acc: 0.5000 - val_loss: 2.8753 - val_acc: 0.0000e+00
Epoch 5/20
6/6 [==============================] - 0s 601us/sample - loss: 1.3176 - acc: 0.5000 - val_loss: 2.8925 - val_acc: 0.0000e+00
Epoch 6/20
6/6 [==============================] - 0s 534us/sample - loss: 1.3135 - acc: 0.5000 - val_loss: 2.9096 - val_acc: 0.0000e+00
Epoch 7/20
6/6 [==============================] - 0s 614us/sample - loss: 1.3094 - acc: 0.5000 - val_loss: 2.9268 - val_acc: 0.0000e+00
Epoch 

In [ ]:
model.fit()