<a href="https://colab.research.google.com/github/LEESUAJE1978/deeplearning_sejong/blob/master/ex08_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0. 텐서플로우 버전 선택

In [1]:
#0. 텐서플로우 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 1.x
except Exception:
    pass

TensorFlow 1.x selected.


1. 패키지 불러오기

In [2]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint #데이터 보기 좋게 출력
pp = pprint.PrettyPrinter(indent =4)
sees = tf.InteractiveSession()

2. 문자 데이터 생성: 원핫 인코딩(one hot encoding)

In [ ]:
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

3. Baic CNN 모델

In [ ]:
sess = tf.InteractiveSession()

with tf.variable_scope('rnn') as scope:
  x_data = np.array([[h,e,l,l,o],
                    [e,o,l,l,l],
                    [l,l,e,e,l]], dtype = np.float32)
  pp.pprint(x_data)

  hidden_size = 2
  cell = tf.nn.rnn_cell.BasicRNNCell(num_units=hidden_size, activation='tanh', reuse=tf.AUTO_REUSE)
  #cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
  outputs,_states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
  sess.run(tf.global_variables_initializer())
  pp.pprint(outputs.eval())

sess.close()

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
array([[[-0.67620766,  0.09317324],
        [ 0.62291193, -0.37915093],
        [ 0.25707006, -0.6701895 ],
        [ 0.41080013, -0.70929354],
        [-0.40081382,  0.64038676]],

       [[ 0.62085587, -0.3380604 ],
        [-0.55598205,  0.68106157],
        [-

/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


4. LSTM 모델

In [ ]:
sess = tf.InteractiveSession()

with tf.variable_scope('lstm') as scope:
  x_data = np.array([[h,e,l,l,o],
                    [e,o,l,l,l],
                    [l,l,e,e,l]], dtype = np.float32)
  pp.pprint(x_data)

  hidden_size = 2
  cell = tf.nn.rnn_cell.LSTMCell(num_units=hidden_size, activation='tanh', reuse= tf.AUTO_REUSE)
  #cell = tf.keras.layers.LSTM(units=hidden_size)
  outputs,_state = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
  sess.run(tf.global_variables_initializer())
  pp.pprint(outputs.eval())

sess.close()

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
array([[[-0.07176895,  0.0704657 ],
        [-0.06609349,  0.14497043],
        [-0.19602728,  0.2672939 ],
        [-0.3077027 ,  0.32779676],
        [-0.19870545,  0.43205282]],

       [[ 0.00157518,  0.10418284],
        [ 0.02987326,  0.24456336],
        [-0.1218581 ,  0.29077116],
        [-0.25626692,  0.34495202],
        [-0.3575235 ,  0.3787851 ]],

       [[-0.10692466,  0.13250427],
        [-0.21947409,  0.2351897 ],
        [-0.18349318,  0.2511792 ],
        [-0.17772219,  0.29021627],
        [-0.31494048,  0.3883306 ]]], dtype=float32)


/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


5. GRU 모델

In [ ]:
sess = tf.InteractiveSession()

with tf.variable_scope('GRU') as scope:
  x_data = np.array([[h,e,l,l,o],
                    [e,o,l,l,l],
                    [l,l,e,e,l]], dtype = np.float32)
  pp.pprint(x_data)

  hidden_size = 2
  cell = tf.nn.rnn_cell.GRUCell(num_units=hidden_size, activation='tanh', reuse= tf.AUTO_REUSE)
  #cell = tf.keras.layers.GRU(units=hidden_size)
  outputs,_states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
  sess.run(tf.global_variables_initializer())
  pp.pprint(outputs.eval())

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
array([[[ 0.10879437,  0.11491187],
        [ 0.2721325 ,  0.07926772],
        [ 0.35406548,  0.15908767],
        [ 0.40857136,  0.23161747],
        [ 0.27648902,  0.13590246]],

       [[ 0.21970713, -0.02335256],
        [ 0.12095518, -0.0888245 ],
        [ 0.2551089 ,  0.00602099],
        [ 0.34369484,  0.09324373],
        [ 0.40303677,  0.1725908 ]],

       [[ 0.17935544,  0.08223594],
        [ 0.29225227,  0.15996996],
        [ 0.37071174,  0.15190203],
        [ 0.41729483,  0.16333917],
        [ 0.45293027,  0.23621723]]], dtype=float32)


/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


7. LSTM 모델을 활용한 예측 

7.1. 데이터 셋 생성

In [3]:
idx2char = ['h', 'i', 'e', 'l', 'o'] #h:0, i:1, e:2, l:3, o:4


In [4]:
h = [1,0,0,0,0]
e = [0,1,0,0,0]
l = [0,0,1,0,0]
o = [0,0,0,1,0]
i = [0,0,0,0,1]

In [5]:
x_data = [[0,1,0,2,3,3]] #hihell
x_one_hot = [[[1,0,0,0,0],
              [0,1,0,0,0],
              [1,0,0,0,0],
              [0,0,1,0,0],
              [0,0,0,1,0],
              [0,0,0,1,0]]]

In [6]:
y_data = [[1,0,2,3,3,4]] #ihello

In [7]:
num_classes = 5  #heloi
input_dim = 5 #1,0,0,0,0
hidden_size = 5 #
batch_size = 1
sequence_length = 6 #6글자
learning_rate = 0.1 #학습률

7.2 플레이스 홀더 생성(Feed to RNN)

In [8]:
X= tf.placeholder(
    tf.float32, [None, sequence_length, input_dim] #batch size, sequence_length, input_dim
)
Y = tf.placeholder(tf.int32, [None, sequence_length]) #batch_size

7.3. 모델 생성(modeling)

In [9]:
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size,reuse= tf.AUTO_REUSE)
initial_state = cell.zero_state(batch_size, tf.float32)
outputs, _state = tf.nn.dynamic_rnn(
    cell, X, initial_state = initial_state, dtype=tf.float32
)

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


7.4 학습


In [13]:
weights = tf.ones([batch_size, sequence_length])
sequence_loss = tf.contrib.seq2seq.sequence_loss(
    logits = outputs, targets = Y, weights = weights
)
loss = tf.reduce_mean(sequence_loss)
train = tf.train.AdamOptimizer(learning_rate= learning_rate).minimize(loss)
prediction = tf.argmax(outputs, axis=2)

7.5.출력

In [14]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for i in range(50):
    l, _ = sess.run([loss, train], feed_dict={X:x_one_hot, Y: y_data})
    result = sess.run(prediction, feed_dict={X: x_one_hot})
    print(i, "loss:", l, "prediction:", result,"true Y:", y_data)
    result_str = [idx2char[c] for c in np.squeeze(result)]
    print("\tPrediction str:", "".join(result_str))

0 loss: 1.5548209 prediction: [[3 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: llllll
1 loss: 1.4615048 prediction: [[3 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: llllll
2 loss: 1.3699063 prediction: [[3 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: llllll
3 loss: 1.2968678 prediction: [[3 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: llllll
4 loss: 1.2404616 prediction: [[3 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: llllll
5 loss: 1.1891657 prediction: [[3 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: llllll
6 loss: 1.1547096 prediction: [[1 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: illlll
7 loss: 1.1146954 prediction: [[1 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: illlll
8 loss: 1.071124 prediction: [[1 3 3 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: illlll
9 loss: 1.0328612 prediction: [[1 3 2 3 3 3]] true Y: [[1, 0, 2, 3, 3, 4]]
	Prediction str: ilelll
10 loss: 0.