<a href="https://colab.research.google.com/github/LEESUAJE1978/deeplearning_sejong/blob/master/ex12_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'해보지 않으면 해낼 수 없다'
https://subinium.github.io/Keras-6-1/

'해보지 않으면 해낼 수 없다'

In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence


In [ ]:
text = '해보지 않으면 해낼 수 없다'

In [ ]:
result = text_to_word_sequence(text)
print(result)

['해보지', '않으면', '해낼', '수', '없다']


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']


In [ ]:
token = Tokenizer()
token.fit_on_texts(docs)



OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [ ]:
print("\n단어 개수: \n", token.word_counts)


단어 개수: 
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [ ]:
print("\n문장 개수: ", token.document_count)


문장 개수:  3


In [ ]:
print("\n 각 단어가 몇 개의 문장에 포함되어 있는가:\n",token.word_docs)


 각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'나누어': 1, '토큰화합니다': 1, '단어를': 1, '먼저': 1, '텍스트의': 2, '각': 1, '단어로': 1, '딥러닝에서': 2, '토큰화해야': 1, '인식됩니다': 1, '수': 1, '토큰화한': 1, '결과는': 1, '있습니다': 1, '사용할': 1})


In [ ]:
print("\n각 단어에 매겨진 인덱스 값:\n", token.word_index)


각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


One-Hot Encoding

In [ ]:
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

In [ ]:
token = Tokenizer()
token.fit_on_texts([text])

In [ ]:
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [ ]:
x=token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [ ]:
from keras.utils import to_categorical

In [ ]:
word_size = len(token.word_index) +1
x = to_categorical(x, num_classes=word_size)

In [ ]:
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


영화리뷰


In [ ]:
docs = ['너무 재밌네요.', '최고예요.', "참 잘 만든 영화예요.", "추천하고 싶은 영화입니다.", "한 번 더 보고 싶네요", "글쎄요","별로예요", "생각보다 지루하네요", "연기가 어색해요", "재미 없어요"]

In [ ]:
from numpy import array


In [ ]:
mark = array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고': 14, '싶네요': 15, '글쎄요': 16, '별로예요': 17, '생각보다': 18, '지루하네요': 19, '연기가': 20, '어색해요': 21, '재미': 22, '없어요': 23}


In [ ]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14, 15], [16], [17], [18, 19], [20, 21], [22, 23]]


In [ ]:
from keras.preprocessing.sequence import pad_sequences

In [ ]:
padded_x = pad_sequences(x, 4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [12 13 14 15]
 [ 0  0  0 16]
 [ 0  0  0 17]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0  0 22 23]]


In [ ]:
word_size = len(token.word_index)+1

In [ ]:
from keras.layers import Dense, Flatten, Embedding

In [ ]:
Embedding(word_size, 8, input_length=4)

In [ ]:
from tensorflow.keras.models import Sequential
import tensorflow as tf

In [ ]:
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer='adam',  loss = 'binary_crossentropy',metrics=['accuracy'])
model.fit(padded_x, mark, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6957 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6934 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6911 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6888 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6865 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6842 - accuracy: 0.8000
Epoch 7/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6819 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6797 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6774 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6751 - accuracy: 0.8000
Epoch 11/20
1/1 [======================

In [ ]:
print("\n Accuracy: %.4f" %(model.evaluate(padded_x, mark)[1]))

1/1 [==============================] - 0s 2ms/step - loss: 0.6499 - accuracy: 0.9000

 Accuracy: 0.9000
